-- up
ALTER TABLE meal ADD COLUMN ai_generated BOOLEAN DEFAULT FALSE;
COMMENT ON COLUMN meal.ai_generated IS 'Indicates if the meal was generated by AI recommendations';

-- down
ALTER TABLE meal DROP COLUMN IF EXISTS ai_generated; 